ClientSettings:
  LocalHost: "127.0.0.1"
  ServerURL: "http://localhost:1042/quantum-auth/v1"
  Port: "6137"
  DeviceLabel: "default-device"
  Email: ""

Ethereum:
  ActiveNetwork: "sepolia"
  ActiveRPC: "Infura"
  Networks:
    sepolia:
      chainId: 11155111
      entryPoint: "0x4337084d9e255ff0702461cf8895ce9e3b5ff108"
      chainIdHex: "0xaa36a7"
      rpcs:
        - name: "Alchemy"
          url: "https://eth-sepolia.g.alchemy.com/v2/"
        - name: "Infura"
          url: "https://sepolia.infura.io/v3/"
    mainnet:
      chainId: 1
      entryPoint: "0x4337084d9e255ff0702461cf8895ce9e3b5ff108"
      chainIdHex: "0x1"
      rpcs:
        - name: "Infura"
          url: "https://mainnet.infura.io/v3/"