ClientSettings:
  LocalHost: "127.0.0.1"
  ServerURL: "http://localhost:1042/quantum-auth/v1"
  Port: "6137"
  DeviceLabel: "default-device"
  Email: ""

Ethereum:
  ActiveNetwork: "sepolia"
  ActiveRPC: "Infura"
  Networks:
    sepolia:
      chainId: 11155111
      entryPoint: "0x433709009B8330FDa32311DF1C2AFA402eD8D009"
      chainIdHex: "0xaa36a7"
      explorer: "https://sepolia.etherscan.io"
      rpcs:
        - name: ""
          url: ""

    base-sepolia:
      chainId: 84532
      chainIdHex: "0x14a34"
      explorer: "https://sepolia.basescan.org"
      entryPoint: "0x433709009B8330FDa32311DF1C2AFA402eD8D009"
      rpcs:
        - name: ""
          url: ""

    mainnet:
      chainId: 1
      entryPoint: "0x433709009B8330FDa32311DF1C2AFA402eD8D009"
      chainIdHex: "0x1"
      explorer: "https://etherscan.io"
      rpcs:
        - name: ""
          url: ""

DefaultAssets:
  Network:
    sepolia:
      - "0x0000000000000000000000000000000000000000"
      - "0x94a9D9AC8a22534E3FaCa9F4e7F2E2cf85d5E4C8"
      - "0xf8Fb3713D459D7C1018BD0A49D19b4C44290EBE5"
    base-sepolia:
      - "0x0000000000000000000000000000000000000000"
    mainnet:
      - "0x0000000000000000000000000000000000000000"
      - "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      - "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      - "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
      - "0x514910771AF9Ca656af840dff83E8264EcF986CA"
      - "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984"