blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://docs.quantumauth.io
    about: Official QuantumAuth documentation.

  - name: ðŸ’¬ Discussions
    url: https://github.com/quantumauth-io/quantumauth-client/discussions
    about: Ask general questions or brainstorm ideas here.
